---
version: '3.9'

services:
  postgres:
    image: docker.io/library/postgres:latest
    hostname: postgres
    container_name: postgres
    networks:
      - bento
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 'megamaxi2022'

  redis:
    image: docker.io/library/redis:latest
    hostname: redis
    container_name: redis
    networks:
      - bento
    ports:
      - "6379:6379"
networks:
 default:
  external:
   name: bento
